spring:
  datasource:
    url: jdbc:mysql://localhost:3306/unid?useSSL=false&allowPublicKeyRetrieval=true&enabledTLSProtocols=TLSv1.2
    username: unid
    password: unid
    driver-class-name: com.mysql.cj.jdbc.Driver